### ISSUE TITLE
[RFC] Pipelining/1v1 match implementation idea

### ISSUE THREAD

**Issue by seelengxd** [uniconhq/unicon-backend#19]
this looks kinda complicated idk if i am overthinking things (idea v1)

# Phase 1: first convert testcase to use **pipelining**
<img width="903" alt="image" src="https://github.com/user-attachments/assets/eeae9732-6a62-4105-a877-e215f7d4d1a9">

## Problem I can already see with this approach
- **Lost testcase WA status** (i.e. if result = False, set to WA...) that the previous hardcoded approach has. **Runner becomes stupider** unless I intentionally add another node there to set the status again to mimic the hardcoded approach of checking that node and changing status...

### is a node (proposed representation, every step now requires these properties)
```json
{
  "id": 1,
  "inputs": [
    {
      "id": 1,
      "name": "params"
    }
  ],
  "outputs": [
    {
      "id": 1,
      "name": "status"
    },
    {
      "id": 2,
      "name": "stdout"
    },
    {
      "id": 3,
      "name": "stderr"
    }
  ]
}
```

## run(inputs): outputs
A step should have a run method, that given the inputs (dict with all keys in inputs), return all keys of outputs.

## A link
```
{
    id: 1,
    from_node_id: 1,
    from_socket_id: 2,
    to_node_id: 2,
    to_socket_id: 1
}
```

## New steps
- Constant step
  - 0 inputs, 
- Input step (special constant step actually)
  - Only 1, 0 inputs, any number of outputs (>= 1) 
- Output step
  - Only 1, 0 outputs, any number of inputs (>= 1) 

## Rough idea of how I think the node runner should work
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/f99925a9-657d-4205-955c-6b5a3c47a5c9">
on termination, the runner can start spawning nodes to form, including a copy of the current_node (which i think is necessary for a loop node)

# Phase 2: implementation of a match
with this, a match could still be a programming task
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/0a2df7da-d056-4db5-9e90-75b64577304b">

## New node 
- loop_step
  - definitely the most cursed one implementation wise
  - unlike other nodes that just activate all its links, this node programmatically activates one link 

## Future improvements
(i.e. there are some flaws but this looks complicated enough already (maybe we are cooked))
-  Loop node doesn't actually need output/status on the first interation

**Comment by shenyih0ng** [comment]
We can probably shift the responsibility of setting the status (e.g. `WA`) back to the `ProgrammingTask` which takes the result of running the test case and compares it with **expected test case result**. The intuition is that the runner that runs the test case do not have to know what exactly is the status, instead it just runs the compute graph.

In our test data we are implicitly assuming that `MatchStringStep` checks for a correct match, but now I am leaning towards it simply be a step that **computes whether it is a match or not**. Subsequently, this match result will be passed into another node that accumulates the previous output and computes a final result that represents the test case result. With this we can do test cases that accepts (`Status.Ok`) non-matches. It is same as your suggestion for adding a extra node but I think this gives us more flexibility while keeping runner simple.
